create table
  public.active_rentals (
    id bigint generated by default as identity,
    checkout timestamp with time zone not null default now(),
    checkin timestamp with time zone null,
    item_id integer null,
    constraint active_rentals_pkey primary key (id),
    constraint public_active_rentals_item_id_fkey foreign key (item_id) references items_plan (id)
  ) tablespace pg_default;

  create table
  public.items_ledger (
    id integer generated by default as identity,
    created_at timestamp with time zone not null default now(),
    qty_change integer null,
    item_id integer null,
    item_sku text null,
    credit_change integer null,
    constraint items_ledger_pkey primary key (id),
    constraint public_items_ledger_item_id_fkey foreign key (item_id) references items_plan (id)
  ) tablespace pg_default;

  create table
  public.items_plan (
    id integer generated by default as identity,
    type text not null,
    price integer null,
    mod_id integer null,
    sku text null,
    rental boolean null,
    constraint items_plan_pkey primary key (id),
    constraint public_items_plan_mod_id_fkey foreign key (mod_id) references mods_plan (id)
  ) tablespace pg_default;

  create table
  public.mods_ledger (
    id integer generated by default as identity,
    created_at timestamp with time zone not null default now(),
    qty_change integer null,
    mod_id integer null,
    mod_sku text null,
    credit_change integer null,
    constraint mods_ledger_pkey primary key (id),
    constraint public_mods_ledger_mod_id_fkey foreign key (mod_id) references mods_plan (id)
  ) tablespace pg_default;

  create table
  public.mods_plan (
    id integer generated by default as identity,
    sku text not null,
    attached_item_id integer null,
    markup integer null,
    compatible text[] null,
    constraint mods_plan_pkey primary key (id),
    constraint public_mods_plan_attached_item_id_fkey foreign key (attached_item_id) references items_plan (id)
  ) tablespace pg_default;